name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: alpine-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build scripts/docker/alpine --file scripts/docker/alpine/Dockerfile --tag pdal-julia:$(date +%s)
